// This file is auto-generated by scripts/setup-env.sh during build
// Do not edit manually
export const environment = {
  production: true,
  bypassAuth: false,
  justTcgApiKey: 'tcg_3b59c0a16e5b4bd384f0c2ec2e9c2a9c',
  supabaseUrl: 'https://utlptclknauqxzhgymsd.supabase.co',
  supabaseAnonKey: 'sb_publishable_nygQBRM8gUYEn-W158WaJQ_MkPOHyyG',
};
