// This file is auto-generated by scripts/setup-env.sh during build
// Do not edit manually
export const environment = {
  production: true,
  bypassAuth: false,
  justTcgApiKey: 'YOUR_JUSTTCG_API_KEY',
  supabaseUrl: 'YOUR_SUPABASE_URL',
  supabaseAnonKey: 'YOUR_SUPABASE_ANON_KEY',
};
