// This file is auto-generated by scripts/setup-env.sh during build
// Do not edit manually
export const environment = {
  production: true,
  supabase: {
    url: 'YOUR_SUPABASE_URL',
    anonKey: 'YOUR_SUPABASE_ANON_KEY',
  },
  bypassAuth: false,
  justTcgApiKey: 'YOUR_JUSTTCG_API_KEY',
};
