#!/bin/bash

# Setup environment variables for Angular build
# This script is run by Netlify before the build

# Ensure environments directory exists
mkdir -p card-inventory/src/environments

# Create development environment file
cat > card-inventory/src/environments/environment.ts <<EOF
export const environment = {
  production: false,
  supabase: {
    url: '${SUPABASE_URL:-https://utlptclknauqxzhgymsd.supabase.co}',
    anonKey: '${SUPABASE_ANON_KEY:-sb_publishable_nygQBRM8gUYEn-W158WaJQ_MkPOHyyG}',
  },
  bypassAuth: false,
  justTcgApiKey: '${JUSTTCG_API_KEY:-tcg_3b59c0a16e5b4bd384f0c2ec2e9c2a9c}',
};
EOF

# Create production environment file from Netlify environment variables
cat > card-inventory/src/environments/environment.prod.ts <<EOF
// This file is auto-generated by scripts/setup-env.sh during build
// Do not edit manually
export const environment = {
  production: true,
  supabase: {
    url: '${SUPABASE_URL}',
    anonKey: '${SUPABASE_ANON_KEY}',
  },
  bypassAuth: false,
  justTcgApiKey: '${JUSTTCG_API_KEY}',
};
EOF

echo "Environment variables injected successfully"
