#!/bin/bash

# Setup environment variables for Angular build
# This script is run by Netlify before the build

# Ensure environments directory exists
mkdir -p card-inventory/src/environments

# Display environment variable values
echo "=== Environment Variables ==="
echo "SUPABASE_URL: ${SUPABASE_URL:-'NOT SET'}"
echo "SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:-'NOT SET'}"
echo "JUSTTCG_API_KEY: ${JUSTTCG_API_KEY:-'NOT SET'}"
echo "============================="

# Create development environment file
echo "Creating development environment file..."

cat > "card-inventory/src/environments/environment.ts" <<EOF
export const environment = {
  production: false,
  bypassAuth: false,
  justTcgApiKey: '${JUSTTCG_API_KEY}',
  supabaseUrl: '${SUPABASE_URL}',
  supabaseAnonKey: '${SUPABASE_ANON_KEY}',
};
EOF

# Create production environment file from Netlify environment variables
echo "Creating production environment file..."
cat > "card-inventory/src/environments/environment.prod.ts" <<EOF
// This file is auto-generated by scripts/setup-env.sh during build
// Do not edit manually
export const environment = {
  production: true,
  bypassAuth: false,
  justTcgApiKey: '${JUSTTCG_API_KEY}',
  supabaseUrl: '${SUPABASE_URL}',
  supabaseAnonKey: '${SUPABASE_ANON_KEY}',
};
EOF

echo "Environment variables injected successfully"
echo ""
echo "=== Production Environment File Contents ==="
cat card-inventory/src/environments/environment.prod.ts
echo "============================================="
